### PR TITLE
Support decimal values in \fs and \be

### PR DESCRIPTION
**Pull request by rr-**
@moi15moi please let me know if this is OK

### CODE REVIEW

**Comment by moi15moi** [comment]
This seems good to me

**Comment by rr-** [comment]
Thanks for letting me know but it seems like quite a corner case, in case it turns up in real life we'll do another round of amendments. For now I'll release the fix for \fs and \be.

**Comment by rr-** [comment]
Released as 2.4.1 on PyPI. LMK if there are any problems with the release as it uses a recently introduced Poetry-based build system.

**Comment by moi15moi** [comment]
I don't know if I am doing something wrong, but when I do: pip install ass-tag-parser -U, I stay at the version 2.3.1

Is it because I have python 3.8.5 ?

**Comment by petzku** [comment]
> I don't know if I am doing something wrong, but when I do: pip install ass-tag-parser -U, I stay at the version 2.3.1

You may need to do `pip install -U ass-tag-parser`

**Comment by moi15moi** [comment]
> > I don't know if I am doing something wrong, but when I do: pip install ass-tag-parser -U, I stay at the version 2.3.1
> 
> You may need to do `pip install -U ass-tag-parser`

No, I even uninstall and reinstall it and I still have the version 2.3.1.

**Comment by rr-** [comment]
https://pypi.org/project/ass-tag-parser/#history the new version is there

Maybe your machine is configured to use an outdated PyPI mirror?

**Comment by moi15moi** [comment]
Ok, it was indeed due to the version of python. You upgraded it to python 3.9 when you updated ass-tag-parser to the 2.3.2 version: https://github.com/bubblesub/ass_tag_parser/commit/f195c627ebe6dda0c8ed0f65fd94b7b7de905b8a#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R24

**Pull request merged**
