### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by Luni-4**
Nit: Unfortunately the `Github Actions` aren't enabled for any repository of the organization

### CODE REVIEW

**Comment by rr-** [comment]
BTW in the future please use commit messages that adhere to the established style

**Comment by Luni-4** [comment]
> BTW in the future please use commit messages that adhere to the established style

Ok, sorry. Feel free to force push the repository adding this commit message:

`ci: add github actions`

**Comment by rr-** [comment]
Too busy to do it, just for the future

**Comment by Luni-4** [comment]
> Too busy to do it, just for the future

If you give me the push access to all the repos, I could do it, don't worry.

**Pull request merged**
